### PR TITLE
Fix JS and CSS combination minification

### LINKED ISSUE #14: Problems with processed JS
Hi, I switched my project to use processed JS (i.e. added a YAML FrontMatter block so I can use Liquid) and now the minifier doesn't seem to work.

I want to use Liquid so I can split my JS across multiple files then {% include %} it all at buildtime.

After the minifier runs on the processed JS, I'm seeing that line-breaks have been removed but comments and excess whitespace are still there (which breaks the script due to some single-line comments), and variable/function names are un-uglified.

Know any workarounds?

### LINKED ISSUE #21: Remove JS comments
Since JS comments don't get removed, any JS comments made using `//` end up commenting out the rest of the file.

### PR DESCRIPTION
**Pull request by kenman345**
Closes #21
Closes #14

Basically we were not having the file re-evaluate and use the other compressors when its been put behind a front matter block. I added the change to both Page and Document as I was not sure which was the one absolutely needed but i did test this locally for myself and didnt run into any trouble. Perhaps you can make adjustments if you know something more than I do as I am still new to this.

### CODE REVIEW

File: lib/jekyll-minifier.rb [hunk 1]
```diff
@@ -78,7 +78,22 @@ def write(dest)
       if exclude?(dest, dest_path)
         output_file(dest_path, output)
       else
-        output_html(dest_path, output)
+        case File.extname(dest_path)
```
Comment (chris-huxtable) [inline lib/jekyll-minifier.rb]: Perhaps this should be broken into a new method. DRY

File: lib/jekyll-minifier.rb [hunk 2]
```diff
@@ -92,7 +107,22 @@ def write(dest)
...
```
Comment (chris-huxtable) [inline lib/jekyll-minifier.rb]: ditto

File: lib/jekyll-minifier.rb (hunk 1 above)
Comment (kenman345) [reply lib/jekyll-minifier.rb]: i'm only a few weeks into ruby code, please go ahead and make the changes or suggest them so I can go ahead and do it.

Comment (kenman345) [reply lib/jekyll-minifier.rb]: what if we did the following inside of the Compressor method:
```ruby
def output_compressed(path, content)
	  case File.extname(path)
		  when '.js'
			if path =~ /.min.js$/
              output_file(path, content)
			else
			  output_js(path, content)
			end
		  when '.css'
			if path =~ /.min.css$/
              output_file(path, content)
			else
			  output_css(path, content)
			end
          when '.xml'
            output_html(path, content)
		  else
            output_html(path, content)
		end
	end
```

Then change up the two file types I updated in this PR to us it of the 'else'.

Comment (chris-huxtable) [reply lib/jekyll-minifier.rb]: Its your PR I don't think I can. You can add something like: 

```ruby
def output_compressed(path, context)
  case File.extname(path)
  when '.js'
    if path.end_with?('.min.js')
      output_file(path, context)
    else
      output_js(path, context)
    end
  when '.css'
    if path.end_with?('.min.css')
      output_file(path, context)
    else
      output_css(path, context)
    end
  else
    output_html(path, context)
  end
end
```

and reference it by: 
```ruby
output_compressed(dest_path, output
```

Which I think is pretty much what you put above. Avoid `Regex`, its slow, complicated, and easily messed up.

**Comment by chris-huxtable** [comment]
Looks better. You will have to wait for @digitalsparky for it to be merged.

**Comment by digitalsparky** [comment]
Sorry folks, been super busy lately, merged. thanks for your contribution

**Comment by kenman345** [comment]
no worries, none of the issues actually told you how to fix. I did some digging myself to identify what it might  be and so I made a PR. Thanks for the plugin, cant wait for this to get a release

**Comment by digitalsparky** [comment]
Released
